# Generated by Django 5.0.1 on 2026-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "Document summary"),
                            ("chat", "Document chat"),
                            ("audio", "Audio file"),
                            ("video", "Video file"),
                            ("youtube", "YouTube video"),
                            ("live", "Live recording"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("transcript", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("chapters", models.JSONField(blank=True, default=list)),
                ("messages", models.JSONField(blank=True, default=list)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
