# Generated by Django 5.0.1 on 2026-09-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoryEntry",
        ),
    ]
